'use strict'

module.exports = {
  env: {
    node: true,
    es6: true,
    es2020: true
  },
  plugins: [
    'node'
  ],
  parserOptions: {
    ecmaVersion: 2020
  },
  reportUnusedDisableDirectives: true,
  rules: {

    // [Possible Errors](https://eslint.org/docs/rules/#possible-errors)
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-compare-neg-zero': 'error',
    'no-constant-condition': 'error',
    'no-debugger': 'error',
    'no-dupe-args': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-ex-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-promise-executor-return': 'error',
    'no-setter-return': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unreachable-loop': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'require-atomic-updates': 'error',
    'use-isnan': 'error',
    'valid-typeof': ['error', {requireStringLiterals: true} ],

    // [Best Practices](https://eslint.org/docs/rules/#best-practices)
    'array-callback-return': ['error', {allowImplicit: true}],
    'class-methods-use-this': 'warn',
    'consistent-return': 'error',
    curly: ['error', 'multi-line'],
    'default-case-last': 'error',
    'default-param-last': 'error',
    'dot-location': ['error', 'property'],
    eqeqeq: ['error', 'always', {null: 'ignore'}],
    'grouped-accessor-pairs': 'error',
    'guard-for-in': 'error',
    'no-alert': 'error',
    'no-case-declarations': 'error',
    'no-else-return': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-label': 'error',
    'no-fallthrough': 'error',
    'no-floating-decimal': 'error',
    'no-invalid-this': 'error',
    'no-loop-func': 'error',
    'no-multi-spaces': 'error',
    'no-multi-str': 'error',
    'no-new-wrappers': 'warn',
    'no-octal-escape': 'warn',
    'no-return-assign': 'error',
    'no-return-await': 'error',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unused-expressions': ['error', { allowShortCircuit: true }],
    'no-unused-labels': 'error',
    'no-useless-concat': 'error',
    'no-useless-escape': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'no-with': 'error',
    'prefer-promise-reject-errors': 'warn',
    'prefer-regex-literals': 'error',
    radix: 'error',
    'require-await': 'error',
    'wrap-iife': 'error',
    yoda: ['error', 'never', {exceptRange: true}],

    // [Strict Mode](https://eslint.org/docs/rules/#strict-mode)
    strict: ['error', 'global'],

    // [Variables](https://eslint.org/docs/rules/#variables)
    'init-declarations': 'error',
    'no-delete-var': 'error',
    'no-label-var': 'error',
    'no-shadow': 'error',
    'no-undef': 'error',
    'no-undef-init': 'error',
    'no-unused-vars': [
      'error', {
        args: 'none',
        caughtErrors: 'all',
        caughtErrorsIgnorePattern: '^ignore'
      }],

    // [Stylistic Issues](https://eslint.org/docs/rules/#stylistic-issues)
    'array-element-newline': ['error', 'consistent'],
    'block-spacing': ['error', 'always'],
    'brace-style': ['error', '1tbs'],
    'comma-dangle': ['error', 'never'],
    'comma-spacing': 'error',
    'comma-style': ['error', 'last'],
    'computed-property-spacing': 'error',
    'eol-last': 'error',
    'func-call-spacing': 'error',
    'func-name-matching': 'error',
    'func-names': ['error', 'as-needed'],
    'func-style': ['error', 'declaration', {allowArrowFunctions: true}],
    'function-call-argument-newline': ['error', 'consistent'],
    'function-paren-newline': ['error', 'consistent'],
    'implicit-arrow-linebreak': ['error', 'beside'],
    indent: ['error', 2, {SwitchCase: 1}],
    'key-spacing': 'error',
    'keyword-spacing': 'error',
    'linebreak-style': 'error',
    'lines-between-class-members': 'error',
    'max-len': ['error', 80],
    'max-params': ['error', 4],
    'multiline-ternary': ['error', 'always-multiline'],
    'new-cap': 'error',
    'new-parens': 'error',
    'newline-per-chained-call': 'error',
    'no-lonely-if': 'error',
    'no-mixed-operators': 'error',
    'no-multiple-empty-lines': ['error', {max: 1}],
    'no-tabs': 'error',
    'no-trailing-spaces': 'error',
    'no-unneeded-ternary': 'error',
    'no-whitespace-before-property': 'error',
    'object-curly-newline': 'error',
    'object-curly-spacing': 'off',
    'object-property-newline': ['error', {allowAllPropertiesOnSameLine: true}],
    'one-var': ['error', 'never'],
    'operator-linebreak': ['error', 'after'],
    'padded-blocks': ['error', 'never'],
    'prefer-object-spread': 'error',
    'quote-props': ['error', 'as-needed'],
    quotes: ['error', 'single'],
    semi: ['error', 'never'],
    'space-before-blocks': 'error',
    'space-before-function-paren': ['error', 'never'],
    'space-in-parens': 'error',
    'space-infix-ops': ['error', { int32Hint: false }],
    'spaced-comment': ['error', 'always'],
    'switch-colon-spacing': 'error',

    // [ECMAScript 6](https://eslint.org/docs/rules/#ecmascript-6)
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': ['error', 'as-needed'],
    'arrow-spacing': 'error',
    'constructor-super': 'error',
    'generator-star-spacing': 'error',
    'no-class-assign': 'error',
    'no-confusing-arrow': 'error',
    'no-const-assign': 'error',
    'no-dupe-class-members': 'error',
    'no-new-symbol': 'error',
    'no-this-before-super': 'error',
    'no-useless-computed-key': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-destructuring': 'error',
    'prefer-spread': 'error',
    'require-yield': 'error',
    'rest-spread-spacing': ['error', 'never'],
    'symbol-description': 'error',
    'yield-star-spacing': ['error', 'before'],

    // [Node.js and CommonJS](https://eslint.org/docs/rules/#deprecated)
    'no-buffer-constructor': 'error',
    'node/handle-callback-err': ['error', 'er'],
    'node/no-callback-literal': 'error',
    'node/no-path-concat': 'error',
    'node/no-unpublished-bin': 'error',
    'node/no-unsupported-features/es-builtins': 'error',
    'node/no-unsupported-features/es-syntax': 'error',
    'node/shebang': 'warn',
    'node/no-deprecated-api': 'error',
    'node/prefer-global/url': 'error'

    // One day?
    // 'no-magic-numbers': 'warn',
    // 'node/no-unsupported-features/node-builtins': 'error'
  }
}
